@php use App\Services\DamageCalculator; @endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Agricultural Damage Report</title>
    <style>
        @page { margin: 28px 32px 40px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9.5px; color: #2f2f2f; }
        h1 { font-size: 16px; margin: 2px 0 0; }
        .office { font-size: 11px; font-weight: bold; color: #5a5de3; }
        .filters { margin-top: 4px; color: #666; }
        table { width: 100%; border-collapse: collapse; }
        .summary { margin: 12px 0; }
        .summary td { width: 25%; background: #f7f7f9; padding: 8px 10px; border: 3px solid #fff; }
        .summary .label { color: #666; font-size: 9px; }
        .summary .value { font-size: 15px; font-weight: bold; color: #5a5de3; }
        .rows th { text-align: left; color: #7e80ff; font-weight: bold; border-bottom: 1.5px solid #ccc; padding: 5px 4px; }
        .rows td { padding: 5px 4px; border-bottom: 0.5px solid #e2e2e2; vertical-align: top; }
        .rows tr { page-break-inside: avoid; }
        .num { text-align: right; }
        .muted { color: #888; }
        .footer { position: fixed; bottom: -24px; left: 0; right: 0; font-size: 8.5px; color: #888; }
    </style>
</head>
<body>
    <div class="footer">Generated by {{ $generatedBy }} on {{ $generatedAt->format('M j, Y g:i A') }} · AGAPAY</div>

    <div class="office">Office of the Municipal Agriculturist — Bontoc</div>
    <h1>Agricultural Damage Report</h1>
    <div class="filters">{{ $filters->describe() }}</div>

    <table class="summary">
        <tr>
            <td><div class="label">Farmers Affected</div><div class="value">{{ DamageCalculator::decimal((float) $summary->farmers) }}</div></td>
            <td><div class="label">Total Area Damaged (ha)</div><div class="value">{{ DamageCalculator::decimal((float) $summary->area) }}</div></td>
            <td><div class="label">Production Loss (MT)</div><div class="value">{{ DamageCalculator::decimal((float) $summary->loss) }}</div></td>
            <td><div class="label">Est. Cost of Damage</div><div class="value">₱{{ DamageCalculator::decimal((float) $summary->cost) }}</div></td>
        </tr>
    </table>

    <table class="rows">
        <thead>
            <tr>
                <th>#</th><th>Name</th><th>RSBSA No.</th><th>Barangay</th><th>Crop / Farm Loc.</th><th>Crop Stage</th>
                <th>Damaged Area (Total/Partial)</th><th class="num">Loss (MT)</th><th class="num">Cost of Damage</th><th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($reports as $report)
                <tr>
                    <td class="muted">{{ $loop->iteration }}</td>
                    <td>{{ $report->beneficiary->fullName() }}</td>
                    <td>{{ $report->beneficiary->rsbsaDisplay() }}</td>
                    <td>{{ $report->barangay->name }}</td>
                    <td>{{ $report->crop->name }}@if ($report->farm_location)<br><span class="muted">{{ $report->farm_location }}</span>@endif</td>
                    <td>{{ $report->stageLabel() }}</td>
                    <td>{{ $report->areaLabel() }}</td>
                    <td class="num">{{ DamageCalculator::decimal((float) $report->loss_mt) }}</td>
                    <td class="num">₱{{ DamageCalculator::decimal((float) $report->cost) }}</td>
                    <td>{{ $report->trashed() ? 'Archived' : $report->statusLabel() }}</td>
                </tr>
            @empty
                <tr><td colspan="10" class="muted">No damage reports for this filter.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
