<?php

use App\Exports\DamageReportExport;
use App\Http\Controllers\DamageExportController;
use App\Models\AuditLog;
use App\Models\DamageReport;
use App\Models\Disaster;
use App\Models\User;
use App\Support\DamageReportFilters;
use Database\Seeders\DatabaseSeeder;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\IOFactory;

beforeEach(function () {
    $this->seed(DatabaseSeeder::class);
    $this->admin = User::where('username', 'Admin_01')->sole();
    $this->typhoon = Disaster::where('name', 'Typhoon Cristina')->sole();
});

it('downloads the filtered reports as xlsx', function () {
    Excel::fake();

    $this->actingAs($this->admin)->get(route('damage.export', ['status' => 'for_validation']))->assertOk();

    Excel::assertDownloaded('agapay-damage-typhoon-cristina-'.today()->format('Y-m-d').'.xlsx', function (DamageReportExport $export) {
        $rows = $export->query()->get();
        $carlos = $rows->first(fn ($r) => $r->beneficiary->first_name === 'Carlos');

        return $export->headings() === [
            'Disaster', 'Farmer', 'RSBSA No.', 'Barangay', 'Crop', 'Farm Location', 'Crop Stage', 'Total Area (ha)', 'Partial Area (ha)',
            'Loss (MT)', 'Cost (₱)', 'Latitude', 'Longitude', 'Photos', 'Status', 'Reported By', 'Date Reported', 'Validated By', 'Validated On',
        ]
            && $rows->count() === 2
            && array_slice($export->map($carlos), 0, 15) === [
                'Typhoon Cristina', 'Carlos Ibanez', $carlos->beneficiary->rsbsaDisplay(), 'Bontoc Ili', 'Rice', 'Sitio Ili 5', 'Maturing',
                1.5, 0.0, 6.0, 120000.0, '', '', 0, 'For Validation',
            ];
    });
});

it('writes text cells as text and figures as numbers', function () {
    $report = DamageReport::whereHas('beneficiary', fn ($q) => $q->where('first_name', 'Juan'))->sole();
    $report->beneficiary->forceFill(['first_name' => '=HYPERLINK("http://x","Click")'])->saveQuietly();
    $path = tempnam(sys_get_temp_dir(), 'agapay').'.xlsx';

    $this->actingAs($this->admin);
    $filters = DamageReportFilters::fromRequest(request()->merge(['status' => 'validated']), $this->admin);
    file_put_contents($path, Excel::raw(new DamageReportExport($filters), Maatwebsite\Excel\Excel::XLSX));
    $sheet = IOFactory::load($path)->getActiveSheet();
    $row = collect(range(2, $sheet->getHighestRow()))->first(fn ($r) => str_starts_with((string) $sheet->getCell("B{$r}")->getValue(), '=HYPERLINK'));

    expect($row)->not->toBeNull()
        ->and($sheet->getCell("B{$row}")->getDataType())->toBe(DataType::TYPE_STRING)
        ->and($sheet->getCell("J{$row}")->getDataType())->toBe(DataType::TYPE_NUMERIC)
        ->and($sheet->getCell("J{$row}")->getValue())->toEqual(5.4);
});

it('generates the pdf with the summary and rows', function () {
    $response = $this->actingAs($this->admin)->get(route('damage.pdf'))->assertOk()
        ->assertHeader('content-type', 'application/pdf')
        ->assertDownload('agapay-damage-typhoon-cristina-'.today()->format('Y-m-d').'.pdf');

    expect(substr($response->getContent(), 0, 4))->toBe('%PDF');
});

it('renders the pdf view with the filters, totals and farmers', function () {
    $this->actingAs($this->admin);
    $filters = DamageReportFilters::fromRequest(request(), $this->admin);

    $html = view('damage.pdf', DamageExportController::pdfData($filters, $this->admin))->render();

    expect($html)->toContain('Agricultural Damage Report')
        ->toContain('Typhoon Cristina (Jul 20, 2026) · Barangay: All · Status: All')
        ->toContain('₱738,000')
        ->toContain('Juan Dela Cruz')->toContain('Liza Domingo')
        ->toContain('Generated by '.$this->admin->name);
});

it('generates empty files for an empty filter', function () {
    $flood = Disaster::where('name', 'Southwest Monsoon Flooding')->sole();
    Excel::fake();

    $this->actingAs($this->admin)->get(route('damage.pdf', ['disaster' => $flood->id]))->assertOk()->assertHeader('content-type', 'application/pdf');
    $this->get(route('damage.export', ['disaster' => $flood->id]))->assertOk();
    Excel::assertDownloaded('agapay-damage-southwest-monsoon-flooding-'.today()->format('Y-m-d').'.xlsx', fn (DamageReportExport $e) => $e->query()->count() === 0);
});

it('handles a long list in the pdf', function () {
    DamageReport::factory()->count(150)->create(['disaster_id' => $this->typhoon->id]);

    $this->actingAs($this->admin)->get(route('damage.pdf'))->assertOk()->assertHeader('content-type', 'application/pdf');
});

it('limits excel to exporters and the pdf to damage viewers', function (string $username, int $excel) {
    Excel::fake();
    $this->actingAs(User::where('username', $username)->sole());

    $this->get(route('damage.export'))->assertStatus($excel);
    $this->get(route('damage.pdf'))->assertOk();
})->with([
    ['Admin_01', 200],
    ['Agritech_02', 403],
    ['Encoder_03', 403],
]);

it('audits both downloads', function () {
    Excel::fake();
    $this->actingAs($this->admin)->get(route('damage.export'));
    $this->get(route('damage.pdf'));

    expect(AuditLog::where('action', 'Exported Damage Reports')->sole()->new_values)
        ->toBe(['filters' => 'Typhoon Cristina (Jul 20, 2026) · Barangay: All · Status: All', 'rows' => 6])
        ->and(AuditLog::where('action', 'Generated Damage Report PDF')->sole()->new_values['rows'])->toBe(6);
});

it('links the list buttons to the downloads with the current filters', function () {
    $this->actingAs($this->admin)->get('/damage-reports?status=validated')
        ->assertSee(route('damage.export', ['disaster' => $this->typhoon->id, 'barangay' => 'all', 'status' => 'validated']))
        ->assertSee(route('damage.pdf', ['disaster' => $this->typhoon->id, 'barangay' => 'all', 'status' => 'validated']));
});

it('caps the pdf rows and points to excel for the rest', function () {
    config(['agapay.damage_pdf_max_rows' => 3]);
    $this->actingAs($this->admin);

    $data = DamageExportController::pdfData(DamageReportFilters::fromRequest(request(), $this->admin), $this->admin);
    $html = view('damage.pdf', $data)->render();

    expect($data['reports'])->toHaveCount(3)
        ->and($html)->toContain('Showing the first 3 of 6 reports — use Export to Excel for the full list.')
        ->toContain('₱738,000');
});
