<?php

use App\Models\AuditLog;
use App\Models\DistributionCycle;
use App\Models\GeneratedReport;
use App\Models\InterventionRecord;
use App\Models\User;
use App\Services\ReportService;
use App\Support\ReportCriteria;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Support\Facades\Storage;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\IOFactory;

beforeEach(function () {
    Storage::fake('local');
    $this->seed(DatabaseSeeder::class);
    $this->admin = User::where('username', 'Admin_01')->sole();
    $this->agritech = User::where('username', 'Agritech_02')->sole();
    $this->encoder = User::where('username', 'Encoder_03')->sole();
    $this->cycle = DistributionCycle::where('code', '2026-Q3')->sole();
});

function reportInput(array $overrides = []): array
{
    return [
        'program' => 'all', 'format' => 'pdf', 'start_date' => '', 'end_date' => '',
        'distribution_cycle_id' => DistributionCycle::where('code', '2026-Q3')->value('id'),
        ...$overrides,
    ];
}

it('shows the Figma form for each role', function (string $username) {
    $this->actingAs(User::where('username', $username)->sole())->get('/reports')->assertOk()
        ->assertSee('REPORT GENERATION')
        ->assertSeeInOrder(['Reports', 'Program', 'Program: All (DA &amp; LGU)', 'Export Format', 'Format: PDF',
            'Start Date', 'End Date', 'Distribution Cycle', 'Cycle: 2026-Q3 Dry Season', 'Generate Report'], false)
        ->assertSee('<option value="'.$this->cycle->id.'" selected', false);
})->with(['Admin_01', 'Agritech_02', 'Encoder_03']);

it('generates a pdf and keeps it in the history', function () {
    $response = $this->actingAs($this->agritech)->post('/reports', reportInput())->assertOk()
        ->assertHeader('content-type', 'application/pdf')
        ->assertDownload('agapay-report-2026-q3-all-'.today()->format('Y-m-d').'.pdf');

    $report = GeneratedReport::sole();
    expect(substr($response->streamedContent(), 0, 4))->toBe('%PDF')
        ->and($report)->user_id->toBe($this->agritech->id)->format->toBe('pdf')->program->toBe('all')
        ->rows->toBe(InterventionRecord::where('distribution_cycle_id', $this->cycle->id)->count())
        ->and(Storage::disk('local')->exists($report->path))->toBeTrue()
        ->and(AuditLog::where('action', 'Generated Distribution Report')->sole())
        ->record_label->toBe($report->file_name)
        ->new_values->toMatchArray(['cycle' => '2026-Q3 Dry Season', 'program' => 'All (DA & LGU)', 'format' => 'PDF']);

    $this->get('/reports')->assertSeeInOrder(['Generated Reports', '2026-Q3 Dry Season', 'All (DA &amp; LGU)', 'All dates', 'PDF', 'Download'], false);
});

it('renders the report sections in the pdf view', function () {
    $criteria = new ReportCriteria($this->cycle);
    $html = view('reports.pdf', [
        ...app(ReportService::class)->build($criteria), 'generatedBy' => 'Tester', 'generatedAt' => now(), 'maxRows' => 1000,
    ])->render();

    expect($html)->toContain('Distribution Monitoring Report')
        ->toContain('Cycle: 2026-Q3 Dry Season · Program: All (DA &amp; LGU) · Dates: All dates')
        ->toContain('Per Intervention')->toContain('Per Barangay')->toContain('Beneficiary List')->toContain('Inventory Used')
        ->toContain('Generated by Tester');
});

it('generates an excel workbook with five sheets', function () {
    $this->actingAs($this->admin)->post('/reports', reportInput(['format' => 'xlsx', 'program' => 'da']))->assertOk()
        ->assertDownload('agapay-report-2026-q3-da-'.today()->format('Y-m-d').'.xlsx');

    $book = IOFactory::load(Storage::disk('local')->path(GeneratedReport::sole()->path));
    expect($book->getSheetNames())->toBe(['Summary', 'Per Intervention', 'Per Barangay', 'Beneficiaries', 'Inventory Used']);

    $perIntervention = $book->getSheetByName('Per Intervention');
    expect($perIntervention->getCell('A1')->getValue())->toBe('Program')
        ->and($perIntervention->getCell('A2')->getValue())->toBe('DA')
        ->and($perIntervention->getCell('D2')->getDataType())->toBe(DataType::TYPE_NUMERIC);
});

it('rejects bad dates and cycles', function (array $overrides, string $field, string $message) {
    $this->actingAs($this->encoder)->from('/reports')->post('/reports', reportInput($overrides))
        ->assertRedirect('/reports')->assertSessionHasErrors([$field => $message]);

    expect(GeneratedReport::count())->toBe(0);
})->with([
    'end before start' => [['start_date' => '2026-08-10', 'end_date' => '2026-08-01'], 'end_date', 'The end date cannot be before the start date.'],
    'future start' => [fn () => ['start_date' => now()->addDay()->toDateString()], 'start_date', 'Dates cannot be in the future.'],
    'unknown cycle' => [['distribution_cycle_id' => 999], 'distribution_cycle_id', 'Choose a distribution cycle.'],
    'no cycle' => [['distribution_cycle_id' => ''], 'distribution_cycle_id', 'Choose a distribution cycle.'],
    'forged program' => [['program' => 'xyz'], 'program', 'Choose a program.'],
    'forged format' => [['format' => 'docx'], 'format', 'Choose PDF or Excel.'],
]);

it('caps the pdf beneficiary list', function () {
    config(['agapay.report_pdf_max_rows' => 3]);
    $criteria = new ReportCriteria($this->cycle);
    $data = app(ReportService::class)->build($criteria);
    $html = view('reports.pdf', [...$data, 'generatedBy' => 'Tester', 'generatedAt' => now(), 'maxRows' => 3])->render();

    expect($html)->toContain('Showing the first 3 of '.count($data['beneficiaries']).' beneficiary rows — choose Excel for the full list.');
});

it('lists history for the owner and everything for the admin', function () {
    $this->actingAs($this->encoder)->post('/reports', reportInput());
    $this->actingAs($this->agritech)->post('/reports', reportInput(['program' => 'lgu']));

    $this->actingAs($this->encoder)->get('/reports')->assertSee($this->encoder->name)->assertDontSee('>LGU<', false);
    $this->actingAs($this->admin)->get('/reports')->assertSee($this->encoder->name)->assertSee($this->agritech->name);
});

it('downloads a past report as generated', function () {
    $this->actingAs($this->encoder)->post('/reports', reportInput());
    $report = GeneratedReport::sole();
    $stored = Storage::disk('local')->get($report->path);
    InterventionRecord::where('distribution_cycle_id', $this->cycle->id)->firstOrFail()->delete();

    $response = $this->get(route('reports.download', $report))->assertOk()->assertDownload($report->file_name);
    expect($response->streamedContent())->toBe($stored);
});

it('hides other users reports', function () {
    $this->actingAs($this->encoder)->post('/reports', reportInput());
    $report = GeneratedReport::sole();

    $this->actingAs($this->agritech)->get(route('reports.download', $report))->assertNotFound();
    $this->actingAs($this->admin)->get(route('reports.download', $report))->assertOk();
});

it('explains a report file that is gone', function () {
    $this->actingAs($this->encoder)->post('/reports', reportInput());
    $report = GeneratedReport::sole();
    Storage::disk('local')->delete($report->path);

    $this->get(route('reports.download', $report))->assertRedirect(route('reports.index'))
        ->assertSessionHasErrors(['report' => 'This report file is no longer available — generate it again.']);
});

it('pluralises units and right-aligns figures in the pdf', function () {
    $criteria = new ReportCriteria($this->cycle);
    $html = view('reports.pdf', [
        ...app(ReportService::class)->build($criteria), 'generatedBy' => 'Tester', 'generatedAt' => now(), 'maxRows' => 1000,
    ])->render();

    expect($html)->toContain('2 sacks')->not->toContain('2 sack<')->not->toContain('0 sack<')
        ->toContain('.rows th.num');
});
