@php
    $decimal = fn ($value) => \App\Services\DamageCalculator::decimal((float) $value);
    // "2 sacks", "1 sack", "5 L"; no unit for cash aid.
    $amount = fn ($value, string $unit) => trim($decimal($value).' '.($unit === '' || $unit === 'L' ? $unit : \Illuminate\Support\Str::plural($unit, (float) $value == 1 ? 1 : 2)));
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Distribution Monitoring Report</title>
    <style>
        @page { margin: 28px 32px 40px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9.5px; color: #2f2f2f; }
        h1 { font-size: 16px; margin: 2px 0 0; }
        h2 { font-size: 11.5px; margin: 16px 0 6px; color: #5a5de3; }
        .office { font-size: 11px; font-weight: bold; color: #5a5de3; }
        .criteria { margin-top: 4px; color: #666; }
        table { width: 100%; border-collapse: collapse; }
        .summary { margin-top: 12px; }
        .summary td { width: 25%; background: #f7f7f9; padding: 8px 10px; border: 3px solid #fff; }
        .summary .label { color: #666; font-size: 9px; }
        .summary .value { font-size: 15px; font-weight: bold; color: #5a5de3; }
        .rows th { text-align: left; color: #7e80ff; border-bottom: 1.5px solid #ccc; padding: 4px; }
        .rows td { padding: 4px; border-bottom: 0.5px solid #e2e2e2; vertical-align: top; }
        .rows tr { page-break-inside: avoid; }
        .rows th.num, .rows td.num, .num { text-align: right; }
        .muted { color: #888; }
        .footer { position: fixed; bottom: -24px; left: 0; right: 0; font-size: 8.5px; color: #888; }
    </style>
</head>
<body>
    <div class="footer">Generated by {{ $generatedBy }} on {{ $generatedAt->format('M j, Y g:i A') }} · AGAPAY</div>

    <div class="office">Office of the Municipal Agriculturist — Bontoc</div>
    <h1>Distribution Monitoring Report</h1>
    <div class="criteria">Cycle: {{ $criteria['cycle'] }} · Program: {{ $criteria['program'] }} · Dates: {{ $criteria['dates'] }}</div>

    <table class="summary">
        <tr>
            <td><div class="label">Beneficiaries</div><div class="value">{{ number_format($summary['beneficiaries']) }}</div></td>
            <td><div class="label">Assigned</div><div class="value">{{ number_format($summary['assigned']) }}</div></td>
            <td><div class="label">Claimed</div><div class="value">{{ number_format($summary['claimed']) }}</div></td>
            <td><div class="label">Unclaimed</div><div class="value">{{ number_format($summary['unclaimed']) }}</div></td>
        </tr>
    </table>

    <h2>Per Intervention</h2>
    <table class="rows">
        <thead><tr><th>Program</th><th>Intervention</th><th class="num">Assigned</th><th class="num">Claimed</th><th class="num">Unclaimed</th><th class="num">Quantity Distributed</th></tr></thead>
        <tbody>
            @forelse ($interventions as $row)
                <tr><td>{{ $row['source'] }}</td><td>{{ $row['name'] }}</td><td class="num">{{ $row['assigned'] }}</td><td class="num">{{ $row['claimed'] }}</td>
                    <td class="num">{{ $row['unclaimed'] }}</td><td class="num">{{ $amount($row['quantity'], $row['unit']) }}</td></tr>
            @empty
                <tr><td colspan="6" class="muted">No intervention records for these criteria.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Per Barangay</h2>
    <table class="rows">
        <thead><tr><th>Barangay</th><th class="num">Beneficiaries</th><th class="num">Assigned</th><th class="num">Claimed</th><th class="num">Unclaimed</th></tr></thead>
        <tbody>
            @forelse ($barangays as $row)
                <tr><td>{{ $row['name'] }}</td><td class="num">{{ $row['beneficiaries'] }}</td><td class="num">{{ $row['assigned'] }}</td>
                    <td class="num">{{ $row['claimed'] }}</td><td class="num">{{ $row['unclaimed'] }}</td></tr>
            @empty
                <tr><td colspan="5" class="muted">No intervention records for these criteria.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Inventory Used</h2>
    <table class="rows">
        <thead><tr><th>Item</th><th class="num">Quantity Used</th></tr></thead>
        <tbody>
            @forelse ($inventory as $row)
                <tr><td>{{ $row['item'] }}</td><td class="num">{{ $decimal($row['used']) }} {{ $row['unit_label'] }}</td></tr>
            @empty
                <tr><td colspan="2" class="muted">No stock was deducted for these distributions.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2>Beneficiary List</h2>
    @if (count($beneficiaries) > $maxRows)
        <p class="muted">Showing the first {{ $maxRows }} of {{ count($beneficiaries) }} beneficiary rows — choose Excel for the full list.</p>
    @endif
    <table class="rows">
        <thead><tr><th>#</th><th>Name</th><th>RSBSA No.</th><th>Barangay</th><th>Intervention</th><th>Quantity</th><th>Validation</th><th>Claim</th><th>Date Distributed</th></tr></thead>
        <tbody>
            @forelse (array_slice($beneficiaries, 0, $maxRows) as $row)
                <tr><td class="muted">{{ $loop->iteration }}</td><td>{{ $row['name'] }}</td><td>{{ $row['rsbsa'] }}</td><td>{{ $row['barangay'] }}</td><td>{{ $row['program'] }}</td>
                    <td>{{ $row['quantity'] }}</td><td>{{ $row['validation'] }}</td><td>{{ $row['claim'] }}</td><td>{{ $row['date'] }}</td></tr>
            @empty
                <tr><td colspan="9" class="muted">No beneficiaries for these criteria.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
